---
abstract: 'Child with socket support.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Child-Socket
provides:
  Child::Socket:
    file: lib/Child/Socket.pm
    version: 0.001
requires:
  Child: 0.006
  IO::Socket::UNIX: 0
  POSIX: 0
resources:
  bugtracker: http://github.com/exodist/Child-Socket/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Child-Socket
version: 0.001
